/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-01-14 12:00:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import java.io.IOException;
import java.io.*;
import java.lang.*;
import java.util.*;

public final class query9_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.lang");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("java.io");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.IOException");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Edit product</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body bgcolor=\"#D8CEF6\">\r\n");
      out.write("\t<h1>Edit product</h1>\r\n");
      out.write("\t<fieldset>\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<form action=\"query9check.jsp\" method=\"post\">\r\n");

String Product_name="";
String Price="";
String Type="";
String Warehouse="";
String Order="";
String k= request.getParameter("query");
String driver = "com.mysql.jdbc.Driver";
String dbURL = "jdbc:mysql://localhost:3306/BAZA1";
String dbuser = "admin";
String dbpassword = "admin";
Connection theConnection = null;
Connection theConnection2 = null;
Connection theConnection3 = null;
Connection theConnection4 = null;
PreparedStatement theStatement = null;
Statement st=null;
Statement st2=null;
Statement st3=null;
Statement st4=null;
ResultSet rs=null;
ResultSet rs2=null;
ResultSet rs3=null;
ResultSet rs4=null;
ArrayList<String> lista=new ArrayList<String>();
ArrayList<String> lista2=new ArrayList<String>();
ArrayList<String> lista3=new ArrayList<String>();
try{  
    Class.forName(driver);
    theConnection=DriverManager.getConnection(dbURL,dbuser,dbpassword); 
    st=theConnection.createStatement();
    rs=st.executeQuery("SELECT * from PRODUCTS WHERE ID_PRODUCTS="+k+"");
    theConnection2=DriverManager.getConnection(dbURL,dbuser,dbpassword); 
    st2=theConnection2.createStatement();
    rs2=st2.executeQuery("SELECT * from TYPES");
    theConnection3=DriverManager.getConnection(dbURL,dbuser,dbpassword); 
    st3=theConnection3.createStatement();
    rs3=st3.executeQuery("SELECT * from WAREHOUSES");
    theConnection4=DriverManager.getConnection(dbURL,dbuser,dbpassword); 
    st4=theConnection4.createStatement();
    rs4=st4.executeQuery("SELECT * from ORDERS");
   while(rs.next()){
   Product_name=rs.getString(2);		
   Price=rs.getString(3);
   Type=rs.getString(4);
   Warehouse=rs.getString(5);
   Order=rs.getString(6);
   }
	while(rs2.next()){
		lista.add(rs2.getString(2));
	}
	while(rs3.next()){
		lista2.add(rs3.getString(2));
	}
	while(rs4.next()){
		lista3.add(rs4.getString(1));
	}


}

catch(Exception e){
 System.out.println("Exception occured! "+e.getMessage()+" "+e.getStackTrace());
 
} 

      out.write("\t\t\t\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"ID_Products\" value=");
      out.print(request.getParameter("query") );
      out.write(">\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<br />Product name:<input type=\"text\" name=\"Products_name\" value=\"");
      out.print(Product_name+" " );
      out.write("\">\r\n");
      out.write("\t\t\t\t <br />Price:<input type=\"text\" name=\"Price\" value=\"");
      out.print(Price );
      out.write("\"> <br />\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Type</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"ID_Types\">\r\n");
      out.write("\t\t\t\t\t<option value=");
      out.print(Type );
      out.write('>');
      out.print(lista.get(Integer.parseInt(Type)-1) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");

					
					for (int i=0;i<lista.size();i++){
						if(i!=Integer.parseInt(Type)-1){
						
      out.write("<option value=");
      out.print(i+1 );
      out.write('>');
      out.print(lista.get(i) );
      out.write("</option>");

					}
						
					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Warehouse</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"ID_Warehouses\">\r\n");
      out.write("\t\t\t\t\t<option value=");
      out.print(Warehouse );
      out.write('>');
      out.print(lista2.get(Integer.parseInt(Warehouse)-1) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

					for (int i=0;i<lista2.size();i++){
						if(i!=Integer.parseInt(Warehouse)-1){
						
      out.write("<option value=");
      out.print(i+1 );
      out.write('>');
      out.print(lista2.get(i) );
      out.write("</option>");

					}
					}
					
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>Order</td>\r\n");
      out.write("\t\t\t\t\t<td><select name=\"ID_Orders\"value=\"Order ");
      out.print(Order );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
if(Integer.parseInt(Order)==0){
								
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t<option value=\"0\">-</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

							for (int i=1;i<lista3.size();i++){
								if(i!=Integer.parseInt(Order)-1){
								
      out.write("<option value=");
      out.print(i );
      out.write(">Order ");
      out.print(lista3.get(i) );
      out.write("</option>");

							}
							}
							}
							
							else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option value=");
      out.print(Order );
      out.write(">Order ");
      out.print(lista3.get(Integer.parseInt(Order)) );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value=\"0\">-</option>\r\n");
      out.write("\t\t\t\t\t\t\t");

					for (int i=1;i<lista3.size();i++){
						if(i!=Integer.parseInt(Order)){
						
      out.write("<option value=");
      out.print(i );
      out.write(">Order ");
      out.print(lista3.get(i) );
      out.write("</option>");

					}
					}
							}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("                    \r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><br />\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"Submit\" name=\"bt\" /></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\t</fieldset>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
